apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
        - name: tickets
          image: samoz93/tickets
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: basic-secrets
                  key: JWT_KEY
            - name: MONGO_URI
              value: "mongodb://tickets-mongo-s:27017/tickets"
            - name: PORT
              value: "3012"
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-s
spec:
  selector:
    app: tickets
  ports:
    - protocol: TCP
      port: 3012
      name: tickets
      targetPort: 3012
